export * from "./assign.routes.js"
export * from "./auth.routes.js"
export * from "./course.routes.js"
export * from "./student.routes.js"
export * from "./teacher.routes.js"
export * from "./user.routes.js"