export * from "./auth.controller.js"
export * from "./user.controller.js"
export * from "./course.controller.js"
export * from "./teacher.controller.js"
export * from "./student.controller.js"
export * from "./assign.controller.js"
export * from "./homework.controller.js"
export * from "./lesson.controller.js"